### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by remicollet** [runkit7/runkit7#195]
For now, build fails

```
/dev/shm/BUILD/php74-php-pecl-runkit7-2.0.3/NTS/runkit_import.c: In function 'zif_runkit_import':
/dev/shm/BUILD/php74-php-pecl-runkit7-2.0.3/NTS/runkit_import.c:611:17: error: implicit declaration of function 'do_bind_inherited_class'; did you mean 'do_bind_class'? [-Werror=implicit-function-declaration]
                 do_bind_inherited_class(key, pce);
                 ^~~~~~~~~~~~~~~~~~~~~~~
                 do_bind_class
cc1: all warnings being treated as errors
make[1]: *** [Makefile:198: runkit_import.lo] Error 1
make[1]: *** Waiting for unfinished jobs....

```

**Comment by TysonAndre** [comment]
https://github.com/runkit7/runkit7/pull/194 is in progress for PHP 7.4 - it has test failures that need to be fixed

**Comment by TysonAndre** [comment]
The tests are now working with 7.4 NTS locally. Some features or configurations, such as runkit_import(), ZTS, or 32-bit builds may have issues I've undiscovered.

PHP 7.4 typed properties will need tests for runkit7_import, and for replacements for `*_property_add`/remove
