### ISSUE TITLE
Syntax error in  runkit_common.c (compiling with visual studio 2017?)

### ISSUE THREAD

**Issue by pilathraj** [runkit7/runkit7#132]
C:\projects\runkit7\runkit_common.c(34): warning C4013: 'PHP_RUNKIT_ITERATE_THROUGH_OBJECTS_STORE_BEGIN' undefined; assuming extern returning int
C:\projects\runkit7\runkit_common.c(35): error C2143: syntax error: missing ';' before 'if'
C:\projects\runkit7\runkit_common.c(35): error C2065: 'object': undeclared identifier
C:\projects\runkit7\runkit_common.c(35): error C2223: left of '->ce' must point to struct/union
C:\projects\runkit7\runkit_common.c(36): error C2065: 'object': undeclared identifier
C:\projects\runkit7\runkit_common.c(36): error C2223: left of '->gc' must point to struct/union
C:\projects\runkit7\runkit_common.c(40): error C2065: 'PHP_RUNKIT_ITERATE_THROUGH_OBJECTS_STORE_END': undeclared identifier
C:\projects\runkit7\runkit_common.c(40): error C2143: syntax error: missing ';' before '}'
runkit_functions.c
runkit_import.c
runkit_methods.c
runkit_object_id.c

**Comment by TysonAndre** [comment]
I assume something is wrong with your include path if the macro couldn't be found. Or the wrong visual studio version is used to compile it

Additionally, the issues don't mention the steps you took to install PHP or set up the include path. I'm not sure if you're filing an issue for local runs or appveyor.

See https://github.com/igbinary/igbinary/blob/master/WINDOWS.md#installing-visual-studio

nikic/php-ast is an example with a working appveyor config. Cou

I haven't tested runkit7 with 7.2 on Windows, but it worked with 7.2 on Linux, except for bugs that were already filed.

**Comment by TysonAndre** [comment]
Closing as a duplicate of #131

**Comment by pilathraj** [comment]
Hi TysonAndre,

   I tried built runkit dll for php7.2. I used Appveyor. I found original appveyor.yml  wasn't not working. ( when i tried original, i got similar error https://ci.appveyor.com/project/TysonAndre/runkit7/branch/master). So that i've modified the appveyor.yml file & create task.bat under appveyor dir (My working fork https://github.com/pilathraj/runkit7).  Now i got little progress,  but built was not yet been created.

[ Syntax error] in runkit_common.c
	`	PHP_RUNKIT_ITERATE_THROUGH_OBJECTS_STORE_BEGIN(i)
	if (object->ce == ce) {
	  GC_FLAGS(object) |= IS_OBJ_USE_GUARDS;  // see zend_object_std_init
	  break;
	}
	PHP_RUNKIT_ITERATE_THROUGH_OBJECTS_STORE_END`
When i commented above force, line /* */,  Appveyor start to create a dll files but i faced other issue.

---------
[Error unresolved external symbol]  in runkit.c Refer: https://ci.appveyor.com/api/projects/status/etgndowk01ykirgd?svg=true

runkit.obj : error LNK2019: unresolved external symbol php_runkit_globals_ctor referenced in function zm_startup_runkit
C:\projects\runkit7\x64\Release\php_runkit.dll :

-------------------
